<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{251bf777-cd53-47dc-84fb-a646393ef4d0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbWriteRegs : FB_WriteRegsExample;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbWriteRegs();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>